version: "3"

services:
  mysql:
    platform: "${DOCKER_PLATFORM:-linux/amd64}"
    container_name: "${PROJECT_NAME}_mysql"
    image: mysql:8
    stop_grace_period: 30s
    volumes:
      - ~/mysql-data/itron/wpconnections:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - "3066:3306"
    networks:
      - wpconnections-local

  php:
    depends_on:
      - "mysql"
    build:
      context: ./php-fpm
      args:
        PHP_VER: $PHP_VERSION
    container_name: "${PROJECT_NAME}_php"
    working_dir: /srv/web/
    extra_hosts:
      - "wpconnections.local:host-gateway"
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_IDE_CONFIG: $XDEBUG_IDE_CONFIG
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_CLIENT_PORT: $XDEBUG_PORT
      PHP_XDEBUG_MODE: $XDEBUG_MODE
      PHP_XDEBUG_IDEKEY: $XDEBUG_IDE_KEY
      PHP_EXTENSIONS_DISABLE: $EXTENSIONS_DISABLE
    volumes:
      - ../:/srv/web/
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/php-wpc-overrides.ini
      - ./php-fpm/grc.php.log.conf:/home/wodby/.grc/grc.conf
    networks:
      - wpconnections-local

  nginx:
    platform: "${DOCKER_PLATFORM:-linux/amd64}"
    container_name: "${PROJECT_NAME}_nginx"
    image: nginx:alpine
    working_dir: /srv/web/
    depends_on:
      - php
    volumes:
      - ../:/srv/web/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - wpconnections-local

networks:
  wpconnections-local:
    driver: bridge
