name: PHP Code Styles

env:
  PHP_VER: "8.1"

on:
  push:
    branches: [ "master", "main", "dev" ]
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  php-cs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build CI image
        run: |
          docker build \
            --build-arg PHP_VERSION=${{ env.PHP_VER }} \
            -t wpconnections-ci:${{ env.PHP_VER }} \
            -f Dockerfile.phpunit .

      - name: Run PHPCS
        run: |
          docker run --rm -v "$PWD:/srv/web" \
            wpconnections-ci:${{ env.PHP_VER }} \
            cs:phpcs
