name: Run Tests

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run
        run: |
          sudo apt-get update -y && sudo apt-get -y install composer
          composer install --no-dev
          composer phpunit