name: Unit Tests (Dockerfile)

on:
  push:
    branches: [ "master", "main", "dev" ]
  pull_request:
    types: [synchronize, opened, reopened]

permissions: {}

jobs:
  phpunit:
    name: PHP Unit ${{ matrix.php-version }} / Ramsey ${{ matrix.ramsey-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [ 8.1, 8.2, 8.3, 8.4 ]
        ramsey-version: [ "^1", "^2" ]

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Build PHPUnit image
        run: |
          docker build \
            --build-arg PHP_VERSION=${{ matrix.php-version }} \
            -t wpconnections-phpunit:${{ matrix.php-version }} \
            -f Dockerfile.phpunit .

      - name: Run all tests
        run: |
          docker run --rm -v "$PWD:/srv/web" \
            wpconnections-phpunit:${{ matrix.php-version }} \
            sh -lc 'git config --global --add safe.directory "*" && composer update ramsey/collection --with "ramsey/collection:${{ matrix.ramsey-version }}" --prefer-dist --no-interaction && composer run phpunit && vendor/bin/phpunit -c php-wp-unit.xml'
